### PR TITLE
add filtering feature

### LINKED ISSUE #1: Do not run on cabal files

### PR DESCRIPTION
**Pull request by mizunashi-mana**
Thanks for awesome vscode plugin!
I try resolve #1 and fix it.

### CODE REVIEW

**Comment by vigoo** [comment]
Thanks but this unfortunately does not solve the issue, because both haskell source files and cabal files have the language id `haskell`. It is a good addition though, to filter out manual invocation of the command from non-haskell documents.

Can you extend it to check the file extension too (something like: language id is `haskell` and extension is not `.cabal`)?

**Comment by mizunashi-mana** [comment]
Oh, I missing...

I add extension settings via `Haskell Syntax Plugin`.  This fixed seems to work good.  How about this?

**Comment by mizunashi-mana** [comment]
#1 seems to be resolved now to me.

Should I close this request?

**Comment by vigoo** [comment]
Yes I solved in another way, sorry. (Was not sure about this solution, this extension should not modify the language mapping I think - its the job of the haskell language plugin)

**Comment by mizunashi-mana** [comment]
I see, don't worry and thx for fixed and awesome plugin.

**Pull request closed without merging**
